export const ActionTypes = {
    SET_ALL_NOTES :"SET_ALLNOTES",
    SET_SEARCHED_NOTES : "SET_SEARCHED_NOTES",
    SET_CREATE_NOTES : "SET_CREATE_NOTES",
    SET_UPDATE_NOTE :"SET_UPDATE_NOTE",
    SET_TRASH_VALUE : "SET_TRASH_VALUE",
    SET_TRASH_NOTE : "SET_TRASH_NOTE",
    ADD_TRASH_NOTE : "ADD_TRASH_NOTE" ,
    REMOVE_TRASH_NOTE : "REMOVE_TRASH_NOTE",
    SET_DELETE_NOTE : "SET_DELETE_NOTE"
}